{
    "name": "Fitness Workout",
    "summary": "Exercises, workout plans, and workout tracking",
    "author": "Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/vertical-fitness",
    "maintainer": ["SANTZ IT"],
    "maintainer_email": "contato@santzit.com",
    "category": "Association/Fitness",
    "version": "18.0.4.0.0",
    "license": "AGPL-3",
    "depends": [
        "base",
        "mail",
        "contacts",
        "membership_extension",
    ],
    "data": [
        "security/fitness_security.xml",
        "security/ir.model.access.csv",
        "data/fitness_workout_cron.xml",
        "data/fitness_unit_data.xml",
        "data/fitness_wger_categories_data.xml",
        "data/fitness_wger_equipment_data.xml",
        "data/fitness_wger_muscles_data.xml",
        "views/fitness_unit_views.xml",
        "views/fitness_exercise_views.xml",
        "views/fitness_routine_views.xml",
        "views/fitness_plan_v2_views.xml",
        "views/fitness_workout_views.xml",
        "views/fitness_menu.xml",
    ],
    "demo": [
        "demo/fitness_exercise_demo.xml",
        "demo/fitness_workout_plan_demo.xml",
        "demo/fitness_workout_plan_v2_demo.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
