{
    "name": "Fitness Workout",
    "summary": "Exercises, workout plans, and workout tracking",
    "author": "Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/vertical-fitness",
    "maintainer": ["SANTZ IT"],
    "maintainer_email": "contato@santzit.com",
    "category": "Association/Fitness",
    "version": "18.0.6.0.0",
    "license": "AGPL-3",
    "depends": [
        "base",
        "mail",
        "contacts",
        "fitness_media",
    ],
    "data": [
        "security/fitness_security.xml",
        "security/fitness_media_security.xml",
        "security/ir.model.access.csv",
        "data/fitness_unit_data.xml",
        "views/fitness_unit_views.xml",
        "views/fitness_exercise_views.xml",
        "views/fitness_media_views.xml",
        "views/fitness_workout_plan_views.xml",
        "views/fitness_workout_views.xml",
        "views/fitness_menu.xml",
    ],
    "demo": [
        "demo/fitness_exercise_category_demo.xml",
        "demo/fitness_muscle_demo.xml",
        "demo/fitness_equipment_demo.xml",
        "demo/fitness_exercise_demo.xml",
        "demo/fitness_exercise_media_demo.xml",
        "demo/fitness_workout_plan_demo.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
